using System;

namespace WspolnyInterfejs
{
	public enum Komendy
	{
		LOGOWANIE, REJESTRACJA, LISTA, WYSLIJ_WATEK, ZAPISZ_POST, UTRZYMAJ, NOWY_WATEK, POTWIERDZENIE, NIE_POTWIERDZENIE, OBSERWUJ_WATEK, WATEK_ZMIENIONY
	}
}
